### ISSUE TITLE
Does not work in Ubuntu 20.04, Python 3.8

### ISSUE THREAD

**Issue by davidromerot** [intnull/videotop#2]
I wonder if this project is still active? The last commits appear to be 11 years ago.

I tried to install this module on a recent Ubuntu installation (python 3.8.10) and it does not work. Here are the traces I get:

1. When running as executable: videotop

> Traceback (most recent call last):
>   File "/usr/local/bin/videotop", line 4, in <module>
>     videotop.main()
> AttributeError: module 'videotop' has no attribute 'main'
> 

2. When running using python3 videotop.py

> Traceback (most recent call last):
>   File "videotop.py", line 7, in <module>
>     import youtube_client
>   File "/home/dromero/builds/videotop/youtube_client.py", line 1, in <module>
>     import gdata.youtube
>   File "/home/dromero/.local/lib/python3.8/site-packages/gdata/__init__.py", line 27, in <module>
>     import atom
>   File "/home/dromero/.local/lib/python3.8/site-packages/atom/__init__.py", line 131, in <module>
>     CreateClassFromXMLString = v1_deprecated(
>   File "/home/dromero/.local/lib/python3.8/site-packages/atom/__init__.py", line 97, in mark_deprecated
>     optional_warn_function.func_name = f.func_name
> AttributeError: 'function' object has no attribute 'func_name'

Can you help make this work in newer python versions?
Thanks.
